name: core
version: 0.0.1
publish_to: none
description: Project core module

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  navigation:
    path: ../navigation

  get_it: ^7.2.0
  dio: ^5.1.1
  logger: ^1.3.0
  flutter_bloc: ^8.1.1
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_messaging: ^14.6.5
  firebase_storage: ^11.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

